INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('Marcos', '123');
INSERT INTO ROLES (NAME) VALUES ('PERMISSAO_01');
INSERT INTO ROLES (NAME) VALUES ('PERMISSAO_02');
INSERT INTO ROLES (NAME) VALUES ('PERMISSAO_03');
INSERT INTO USERS_ROLES (ROLES_ID, USERS_ID) VALUES (1, 1);
INSERT INTO USERS_ROLES (ROLES_ID, USERS_ID) VALUES (2, 1);
INSERT INTO USERS_ROLES (ROLES_ID, USERS_ID) VALUES (3, 1);


